### ISSUE TITLE
The icon name "application-menu" is invalid

### ISSUE THREAD

**Issue by danrabbit** [luizaugustomm/tomato#10]
The icon you want is "open-menu"

I've marked your app as "needs fixing". Once this issue is addressed, upload a new release and I'll approve it :)

**Comment by luizaugustomm** [comment]
Where is it in the code, @danrabbit?

**Comment by danrabbit** [comment]
Ah I bet it's because you are using Granite.Widgets.AppMenu. This widget is unmaintained and deprecated. You should use instead [Gtk.MenuButton](https://valadoc.org/gtk+-3.0/Gtk.MenuButton.html)
