### ISSUE TITLE
Use "current window" for screenshot

### ISSUE THREAD

**Issue by danrabbit** [luizaugustomm/tomato#19]
Instead of grabbing a whole screen screenshot, it would be much easier for people to see your app clearly if it were a "current window" screenshot

**Comment by cassidyjames** [comment]
Here are a few I snapped from my machine, with scaling-factor 2:
![screenshot from 2017-04-22 15 16 37](https://cloud.githubusercontent.com/assets/611168/25308329/c378906e-276e-11e7-8abf-4ee01fcbc397.png)
![screenshot from 2017-04-22 15 16 47](https://cloud.githubusercontent.com/assets/611168/25308327/c3753626-276e-11e7-80f9-8532a3e8c555.png)
![screenshot from 2017-04-22 15 16 55](https://cloud.githubusercontent.com/assets/611168/25308330/c38a90d4-276e-11e7-87e0-3fc0fd67c29e.png)

**Comment by cassidyjames** [comment]
And one of the default set up:
![screenshot from 2017-04-22 15 18 25](https://cloud.githubusercontent.com/assets/611168/25308335/f51458ce-276e-11e7-96e5-3b3ce6eacbe6.png)

**Comment by luizaugustomm** [comment]
Thanks, @cassidyjames and @danrabbit!
