### ISSUE TITLE
Minimize to System Tray

### ISSUE THREAD

**Issue by TheAntimist** [luizaugustomm/tomato#22]
I was wondering, if it'd be possible to add a feature where the app has an option to minimize to the system tray instead of to the normal list of apps.

Currently running XUbuntu 17.04

**Comment by luizaugustomm** [comment]
@TheAntimist that is a design decision. elementaryOS HIG discourages creating system tray apps.

**Comment by TheAntimist** [comment]
Ah okay, thanks for the clarification.
