### ISSUE TITLE
Change the Main Window into a transient dialog

### ISSUE THREAD

**Issue by sgpthomas** [luizaugustomm/tomato#23]
![tomato-as-dialog](https://cloud.githubusercontent.com/assets/3752122/25364872/66c770f8-2933-11e7-9f9b-5f843e8814b9.png)
This is just a very crude picture of what I am thinking of. Some gui code would need to change a bit to work better with the dialog. It would be cool to have the whole dialog colored. 

Argument for this: By the nature of this app, the Tomato window is not really meant to keep open and interact with. Instead you interact with it in short bursts. I think transient dialogs fit this purpose well, and look pretty good doing it.

Agenda is an app that does something similar. If you're interested in this idea, I can fill out my code a bit more and submit a pull request.

**Comment by sgpthomas** [comment]
mostly works now :)
Let me know what you think. I'll propose a branch if I can figure out how. 

![tomato-dialog-1](https://cloud.githubusercontent.com/assets/3752122/25535891/a13a6d3c-2c06-11e7-9b53-d7c25adea7ff.png)

![tomato-dialog-2](https://cloud.githubusercontent.com/assets/3752122/25535897/a41c56e6-2c06-11e7-83f8-59cd67c83582.png)

**Comment by luizaugustomm** [comment]
@sgpthomas I don't know. I think it might break a "rule" of elementaryOS HIG:

> Your application will appear native to the desktop and share the same elegant look as default applications.

What do you think @danrabbit and @cassidyjames?

**Comment by danrabbit** [comment]
I've actually been playing with an app that does this. Check out [the css](https://github.com/danrabbit/nimbus/blob/master/data/Application.css)

**Comment by sgpthomas** [comment]
@luizaugustomm if you like the idea, I will keep working on it and refine what I've done so far. i personally think it looks pretty good
